language: node_js
node_js:
- 0.8
notifications:
  email: true
  hipchat:
    rooms:
      secure: fTPZEKAd4jqfU48HK+LD4LNDJwDUHoyNZYUjoMB3coJnn5aIPPDKNqcw+QB3+KZovqfGh7ldyB5Jtqn/qVefSpSvA8hJRFt7Qe6AsfnID/+I+Os16YIaUDd4xYAgBSAx0hSZwDAKCOQ9oRq31SzIZuyToN/e/u+caGJlON6tvHc=
before_install:
- npm install -g grunt-cli
- npm install
